# Define a imagem base
FROM node:18-alpine

# Cria um diretório para o aplicativo
WORKDIR /app

RUN chown node:node /app

# Instala o Nest.js globalmente
RUN npm install -g @nestjs/cli

# Copia os arquivos do projeto
 COPY ["package.json", "package-lock.json*", "./"]

# Instala as dependências
RUN npm install

COPY . .

# Expõe a porta na imagem
EXPOSE ${PORT}

# Inicia o aplicativo
CMD ["npm", "run", "start:dev"]